---
title: "Initial Project Code"
author: "Sarah Brashear"
date: "4/9/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(tidyverse)
library(rstanarm)
library(tidycensus)
library(ggthemes)
library(gt)
library(gtsummary)
library(patchwork)
library(ggdist)


```

```{r, load_data}

# Both datasets were downloaded from the SEDA website, linked in my app. The first
# one, that I call "data" has an observation for each of the ~13,000 public school 
# districts in the country. It contains identifying variables, like district
# names and states, but the three most important for my analysis are:

# meanavg - the mean test score for 5th graders in the district (standardized so
# that scores are comparable between districts and states, and reported in grade-level
# increments. So 5 = knowledge & skills of a 5th grader, 6 = 6th grader, and so on)

# sesavgall - the average Socioeconomic Status of the school district (standardized,
# so the national mean is 0, and each one unit difference is one standard deviation
# difference)

# tot_asmts - the total number of tested students in the district; essentially 
# the total student enrollment of the district +/- a few students who opted out
# of testing or were absent. I use this variable in one of my visualizations.


data <- read_csv("SEDA_App_2021/raw_data/SEDA19.csv",
                 col_types = cols(
                      leaid = col_double(),
                      leanm = col_character(),
                      stateabb = col_character(),
                      mn_asmts = col_double(),
                      meanavg = col_double(),
                      sesavgall = col_double(),
                      fips = col_character(),
                      tot_asmts = col_double(),
                      cellcount = col_double(),
                      mn_grd_eb = col_double(),
                      mn_coh_eb = col_double(),
                      mn_mth_eb = col_double()
                    )
                    )

# The covariates data below includes 10 years of data (from 2008-09 to 2017-18)
# It also includes a ton of other variables for each district in each year, like
# the racial demographics and various subgroups (numbers and percentages for each)

covariates <- read_csv("SEDA_App_2021/raw_data/seda_cov_geodist_poolyr_4.0.csv",
                       col_types = cols(
                          .default = col_double(),
                          sedaleanm = col_character(),
                          locale = col_character(),
                          gslo = col_character()
                        ))
```


```{r, clean_data}
# Since the covariates included 10 years but the data only included 2018, I 
# filtered the covariates to match and then joined the data into one tibble

cov_vars <- covariates %>%
  filter(year == "2018") %>%
  select(sedalea, perind, perasn, perhsp, perblk, perwht,
         perell, perspeced, totenrl) %>%
  
  # I selected only the covariates I was interested in exploring in my models
  # because I knew if I kept them all, more districts may be dropped later
  # when I joined the data
  
  rename(leaid = sedalea)


model_data <- inner_join(data, cov_vars, by = "leaid")

# Down from 13,000 to 12,855 districts that had covariate data available for
# 2018 that was reported and reliable. Not particularly concerned about this 
# because it's only a drop of roughly 1%

```


## Wisdom

```{r, plot1}

data %>%
  
# plotting directly from data rather than model_data since I don't need the 
# covariates for this part, and it's more complete. Might as well include all
# the districts if I can, rather than exclude the ones missing covariate data.
  
  drop_na(sesavgall, meanavg) %>%
  ggplot(aes(x = sesavgall, 
             y = meanavg,
             size = tot_asmts)) +
  geom_point(alpha = .4,
             color = 'royalblue4') +
  
  # No matter how small I make the alpha, it's still way overplotted and hard
  # to see what's going on with all the districts in the country plotted.
  
  geom_hline(yintercept = 5, linetype = "dashed") +
  
  # The horizontal line is a reference line since 5th graders should all be
  # scoring at this level, regardless of SES in theory
  
  geom_smooth(method = "lm", formula = y ~ poly(x, 3), color = "grey15", se = FALSE) +
  labs(title = "SES and Academic Acheivement for each School District",
       subtitle = "There's a strong positive correlation, with a few outliers",
       x = "Average Family Socioeconomic Status",
       y = "Average Student Achievement of 5th Graders",
       caption = "Source: Stanford Educational Data Archive (SEDA)") +
  theme_classic() +
  theme(legend.position = "none") +
  scale_size_continuous(range = c(1, 10))

# This plot tells us there's an obvious positive correlation between these 
# two variables, but that's not surprising or particularly interesting on its own
```

```{r, plot2}

# Since the plot for the whole US is too dense, I decided to make this the 
# interactive part of my app. Testing out what it might look like for just
# one state's data by filtering, though this will work slightly differently in
# the app because the user will be able to choose a state from a dropdown list.

data %>%
  filter(stateabb == "TX") %>%
  drop_na(sesavgall, meanavg) %>%
  ggplot(aes(x = sesavgall, 
             y = meanavg,
             size = tot_asmts)) +
  geom_point(alpha = .4,
             color = 'royalblue4') +
  geom_hline(yintercept = 5, linetype = "dashed") +
  geom_smooth(method = "lm", formula = y ~ poly(x, 3), color = "grey15", se = FALSE) +
  labs(title = "Correlation Between SES and Academic Acheivement",
       subtitle = "Each Bubble is a Public School District",
       
       # My title and subtitle have to be a little more generic since the code
       # is generating the plot on the fly. Not sure how I could code in different
       # titles for different states, but that might be worth exploring if I have
       # time.
       
       x = "Average Family Socioeconomic Status",
       y = "Average Student Achievement of 5th Graders",
       caption = "Source: Stanford Educational Data Archive (SEDA)") +
  theme_classic() +
  theme(legend.position = "none") +
  scale_size_continuous(range = c(1, 10))
```

```{r, fit_1}

# Fit 1 regresses SES on achievement, taking into consideration racial demographics
# Each of the other variables is the percentage of the students that are from 
# that particular racial category. 
# Turns out that these are not significant when SES is already accounted for so 
# I do not use them in my final model. 

fit_1 <- stan_glm(meanavg ~ sesavgall + sesavgall*perind + sesavgall*perasn +
                    sesavgall*perhsp + sesavgall*perblk + sesavgall*perwht, 
                  data = model_data, 
                  seed = 28,
                  refresh = 0)

```

```{r, fit_2}

# Fit two considers non-racial or economic demographics - the percent that are 
# English language learners, special ed, and the size of the school district
# It makes sense that districts with larger than average %s of students in these
# groups would have lower achievement than otherwise expected, so it makes sense
# to include them in the model so we can hold them constant across districts in 
# a new obs if this ends up being the best model. 

fit_2 <- stan_glm(meanavg ~ sesavgall + sesavgall*perell + sesavgall*perspeced, 
                  data = model_data, 
                  seed = 28,
                  refresh = 0)

```

```{r, fit_3}

# Fit three includes the states variable so that I can incorporate states into
# my new obs and look at different posteriors for different states.
# Still makes sense to hold % of language learners and special ed students constant

fit_3 <- stan_glm(meanavg ~ sesavgall + sesavgall*stateabb + perell + perspeced, 
                  data = model_data, 
                  seed = 28,
                  refresh = 0)

```

```{r, fit_4}

# Fit four is the same idea as fit three, but I removed the ELL and special ed
# variables because the regression fails to run on my machine. 

fit_4 <- stan_glm(meanavg ~ sesavgall + sesavgall*stateabb, 
                  data = model_data, 
                  seed = 28,
                  refresh = 0)

# Turns out the reason why these models were failing is because the chains don't
# have enough material to converge after having 50+ controls because of my
# stateabb variable
```


```{r}
# Since I cannot have every state with it's own parameter, I decided to create
# a new variable that indicates Texas, California, or another state

final_data <- model_data %>%
  mutate(state = case_when(stateabb == "TX" ~ 1,
                           stateabb == "CA" ~ 2,
                           stateabb == "MA" ~ 3,
                           stateabb != "TX" |
                           stateabb != "MA" |
                           stateabb != "CA" ~ 0))
```

```{r, fit_5}
fit_5 <- stan_glm(meanavg ~ sesavgall + sesavgall*state, 
                  data = final_data, 
                  seed = 28,
                  refresh = 0)
```

```{r, fit_6}
fit_6 <- stan_glm(meanavg ~ sesavgall + sesavgall*state + perell + perspeced, 
                  data = final_data, 
                  seed = 28,
                  refresh = 0)
```

```{r, loo_compare}

# comparing the models 

loo_fit_1 <- loo(fit_1) 
# loo_fit_1 has elpd_loo of -10860.7 with SE of 91.8


loo_fit_2 <- loo(fit_2) 
# loo_fit_2 has elpd_loo of -8817.3 with SE of 84.3

loo_fit_3 <- loo(fit_3) 

loo_fit_4 <- loo(fit_4)
# loo_fit_4 has elpd_loo of -181737544.5	and SE of 16169052.5

loo_fit_5 <- loo(fit_5)
# elpd_loo of -11946.6	and SE of 93.6	

loo_fit_6 <- loo(fit_6)
# elpd_loo of -8634.0 and SE of 83.4	

loo_compare(loo_fit_5, loo_fit_6)

# Fit 6 is the best model


```



```{r, reg_table}
tbl_regression(fit_6, 
               intercept = TRUE, 
               estimate_fun = function(x) style_sigfig(x, digits = 3)) %>%
  as_gt() %>%
    tab_header(title = "Student Achievement Based on SES", 
               subtitle = "How state predicts academic opportunity") %>%
    tab_source_note(md("SEDA")) %>% 
  cols_label(estimate = md("**Parameter**"))

# I decided not to include this table in my final app because the parameters are
# not particularly meaningful, especially the states parameter since the values
# are designed to indicate which state but not to be interpreted numerically. 
# The posterior does a better job answering my question.
```

```{r, comparative_posterior}

new_obs_1 <- tibble(sesavgall = 0.2053,
                       perell = .1,
                       perspeced = .01,
                       state = c(0, 1, 2, 3))

                       # 0 = all other states
                       # 1 = Texas
                       # 2 = California
                       # 3 = Massachusetts

pe_states <- posterior_epred(fit_6, newdata = new_obs_1) %>% 
  as_tibble() %>%
  mutate_all(as.numeric) %>%
  rename(Others = `1`,
         Texas = `2`,
         California = `3`,
         Massachusetts = `4`)


pe_states %>%
  pivot_longer(names_to = "State",
               values_to = "Student Achievement",
               cols = Texas:Massachusetts) %>%

  ggplot(aes(x = `Student Achievement`)) +
    stat_slab(aes(fill = State))  +
    labs(title = "Predicted Student Achievement by States",
         subtitle = "Districts in Texas Outperform California and Massachusetts",
         x = "Expected Student Achievement for a 5th Grader",
         y = "Probability") +
    theme_classic() 


```

```{r, save_plot1}

ggsave("states_posterior.png", plot = last_plot())

```

```{r, posterior_plot}

new_obs_2 <- tibble(sesavgall = 0.2053,
                       perell = .1,
                       perspeced = .01, 
                       state = c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
                                 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                                 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                                 0, 0, 0, 1, 2, 3))

pe <- posterior_epred(fit_6, newdata = new_obs_2) %>% 
  as_tibble() %>%
  mutate_all(as.numeric) %>%
  pivot_longer(names_to = "Draw",
               values_to = "Achievement",
               cols = `1`:`51`
              )

pe %>%
    ggplot(aes(x = `Achievement`)) +
    geom_histogram(aes(y = after_stat(count/sum(count))),
                   bins = 300,
                   color = 'royalblue4',
                   alpha = .4)  +

    labs(title = "Predicted Student Achievement for the Average School District",
         subtitle = "Districts very likely to achieve slightly above grade level",
         x = "Expected Student Achievement for a 5th Grader",
         y = "Probability") +
    theme_classic() 

```


```{r, save_plot2}

ggsave("posterior.png", plot = last_plot())

```


## Alternate analysis - directly filtering the data before running the posteriors

```{r}
tx_data <- data %>%
  filter(stateabb == "TX") 

data %>%
  filter(stateabb == "TX") %>%
  drop_na(sesavgall, meanavg) %>%
  
  
  ggplot(aes(x = sesavgall, 
             y = meanavg,
             size = tot_asmts,
             # color = ifelse(stateabb == "CA", "blue", "black")
             )) +
  geom_point(alpha = .4,
             color = 'royalblue4') +
  geom_hline(yintercept = 5, linetype = "dashed") +
  geom_smooth(method = "lm", formula = y ~ poly(x, 3), color = "grey15", se = FALSE) +
  labs(title = "Correlation Between SES and Academic Acheivement",
       subtitle = "Each Bubble is a Public School District",
       x = "Average Family Socioeconomic Status",
       y = "Average Student Achievement of 5th Graders",
       caption = "Source: Stanford Educational Data Archive (SEDA)") +
  theme_classic() +
  theme(legend.position = "none") +
  scale_size_continuous(range = c(1, 10))


  geom_point(data = tx_data,
             aes(x = sesavgall,
                 y = meanavg),
             color = 'blue',
             alpha = .5) 
    
                # color=ifelse(stateabb == "CA", 'red', 'blue')))

ca_data <- data %>%
  filter(stateabb == "CA")

ma_data <- data %>%
  filter(stateabb == "MA")
```

```{r}
tx_md <- model_data %>%
  filter(stateabb == "TX")

ca_md <- model_data %>%
  filter(stateabb == "CA")

ma_md <- model_data %>%
  filter(stateabb == "MA")
```


```{r}
tbl_regression(fit_tx, 
               intercept = TRUE, 
               estimate_fun = function(x) style_sigfig(x, digits = 3)) %>%
  as_gt() %>%
    tab_header(title = "Student Achievement Based on SES in Texas", 
               subtitle = "Texas School Districts Fall Near Middle of 50 States") %>%
    tab_source_note(md("Source: Stanford Educational Data Archive (SEDA)")) %>% 
  cols_label(estimate = md("**Parameter**"))
```

```{r}
tbl_regression(fit_ma, 
               intercept = TRUE, 
               estimate_fun = function(x) style_sigfig(x, digits = 3)) %>%
  as_gt() %>%
    tab_header(title = "Student Achievement Based on SES in Massachusetts", 
               subtitle = "Massachusetts School Districts Outperform Most Other States") %>%
    tab_source_note(md("Source: Stanford Educational Data Archive (SEDA)")) %>% 
  cols_label(estimate = md("**Parameter**"))
```

```{r}
tbl_regression(fit_ca, 
               intercept = TRUE, 
               estimate_fun = function(x) style_sigfig(x, digits = 3)) %>%
  as_gt() %>%
    tab_header(title = "Student Achievement Based on SES in California", 
               subtitle = "California School Districts Tend to Underperform") %>%
    tab_source_note(md("Source: Stanford Educational Data Archive (SEDA)")) %>% 
  cols_label(estimate = md("**Parameter**"))
```

```{r}
fit_tx <- stan_glm(meanavg ~ sesavgall + sesavgall*perell + sesavgall*perspeced, 
                  data = tx_md, 
                  seed = 28,
                  refresh = 0)
```

```{r}
fit_ca <- stan_glm(meanavg ~ sesavgall + sesavgall*perell + sesavgall*perspeced, 
                  data = ca_md, 
                  seed = 28,
                  refresh = 0)
```

```{r}
fit_ma <- stan_glm(meanavg ~ sesavgall + sesavgall*perell + sesavgall*perspeced, 
                  data = ma_md, 
                  seed = 28,
                  refresh = 0)
```

```{r}
# This is modeling achievement for districts with low SES only

new_obs_low <- tibble(sesavgall = -0.3082,
                      perell = .1,
                      perspeced = .1
                    )

pe1_tx <- posterior_epred(fit_tx, newdata = new_obs_low) %>% 
  as_tibble() %>%
  mutate_all(as.numeric) 

pe1_ca <- posterior_epred(fit_ca, newdata = new_obs_low) %>% 
  as_tibble() %>%
  mutate_all(as.numeric) 

pe1_ma <- posterior_epred(fit_ma, newdata = new_obs_low) %>% 
  as_tibble() %>%
  mutate_all(as.numeric) 
```

```{r}

Texas_Low <- pe1_tx$`1`
California_Low <- pe1_ca$`1`
Massachusetts_Low <- pe1_ma$`1`

plot_data_1 <- tibble(Texas_Low, California_Low, Massachusetts_Low) 

low_ses_plot <- plot_data_1 %>% 
  rename(Texas = Texas_Low,
         California = California_Low,
         Massachusetts = Massachusetts_Low) %>%
  pivot_longer(cols = `Texas`:`Massachusetts`,
               names_to = "state",
               values_to = "achievement") %>%
  ggplot(aes(x = achievement, 
             fill = state)) +
    geom_histogram(aes(y = after_stat(count/sum(count))),
                   bins = 300)  +
    scale_fill_manual(values = c('royalblue4', 'chartreuse4', "#FC4E07")) +
    labs(title = "Posterior for Student Achievement in School Districts with Low SES",
         subtitle = "California underperforms while Massachusetts overperforms",
         x = "Expected Student Achievement for 5th Graders",
         y = "Probability") +
    scale_y_continuous(labels = scales::percent_format()) +
    theme_classic() +
    theme(legend.position = "bottom")

```

```{r} 

# This is modeling achievement for districts with average SES only

new_obs_mean <- tibble(sesavgall = 0.2053,
                      perell = .1,
                      perspeced = .1
                    )

pe2_tx <- posterior_epred(fit_tx, newdata = new_obs_mean) %>% 
  as_tibble() %>%
  mutate_all(as.numeric) 

pe2_ca <- posterior_epred(fit_ca, newdata = new_obs_mean) %>% 
  as_tibble() %>%
  mutate_all(as.numeric) 

pe2_ma <- posterior_epred(fit_ma, newdata = new_obs_mean) %>% 
  as_tibble() %>%
  mutate_all(as.numeric) 
```

```{r}
# Plot for average SES across the three districts

Texas_Mean <- pe2_tx$`1`
California_Mean <- pe2_ca$`1`
Massachusetts_Mean <- pe2_ma$`1`

plot_data_2 <- tibble(Texas_Mean, California_Mean, Massachusetts_Mean) 

mean_ses_plot <- plot_data_2 %>% 
    rename(Texas = Texas_Mean,
         California = California_Mean,
         Massachusetts = Massachusetts_Mean) %>%
  pivot_longer(cols = `Texas`:`Massachusetts`,
               names_to = "state",
               values_to = "achievement") %>%
  ggplot(aes(x = achievement, 
             fill = state)) +
    geom_histogram(aes(y = after_stat(count/sum(count))),
                   bins = 300)  +
    scale_fill_manual(values = c('royalblue4', 'chartreuse4', "#FC4E07")) +
    labs(title = "Posterior for Student Achievement in School Districts with Average SES",
         subtitle = "The gaps between states are wider here than in Low SES Model",
         x = "Expected Student Achievement for 5th Graders",
         y = "Probability") +
    scale_y_continuous(labels = scales::percent_format()) +
    theme_classic() +
    theme(legend.position = "bottom")
  
```

```{r} 

# This is modeling achievement for districts with high SES only

new_obs_high <- tibble(sesavgall = 0.7831,
                      perell = .1,
                      perspeced = .1)

pe3_tx <- posterior_epred(fit_tx, newdata = new_obs_high) %>% 
  as_tibble() %>%
  mutate_all(as.numeric) 

pe3_ca <- posterior_epred(fit_ca, newdata = new_obs_high) %>% 
  as_tibble() %>%
  mutate_all(as.numeric) 

pe3_ma <- posterior_epred(fit_ma, newdata = new_obs_high) %>% 
  as_tibble() %>%
  mutate_all(as.numeric) 
```

```{r}
# Plot for high SES across the three districts

Texas_High <- pe3_tx$`1`
California_High <- pe3_ca$`1`
Massachusetts_High <- pe3_ma$`1`

plot_data_3 <- tibble(Texas_High, California_High, Massachusetts_High) 

high_ses_plot <- plot_data_3 %>% 
    rename(Texas = Texas_High,
         California = California_High,
         Massachusetts = Massachusetts_High) %>%
  pivot_longer(cols = `Texas`:`Massachusetts`,
               names_to = "state",
               values_to = "achievement") %>%
  ggplot(aes(x = achievement, 
             fill = state)) +
    geom_histogram(aes(y = after_stat(count/sum(count))),
                   bins = 300)  +
    scale_fill_manual(values = c('royalblue4', 'chartreuse4', "#FC4E07")) + 
    labs(title = "Posterior for Student Achievement in Districts with High SES",
         subtitle = "Massachusetts overperforms by largest margin",
         x = "Expected Student Achievement for 5th Graders",
         y = "Probability") +
    scale_y_continuous(labels = scales::percent_format()) +
    theme_classic() +
    theme(legend.position = "bottom")
  
```

```{r}
# using patchwork - don't love how this looks though
# ended up not incorporating this in my final app, but saving the code for future
# reference

low_ses_plot + mean_ses_plot + high_ses_plot +
    plot_annotation(
    title = "Posterior Distribution of the Expected Value of the Change in 
    Proportion of Registered Voters",
    subtitle = "Survey of a 2013 Kenyan Voter Registration Experiment
    \"local + SMS\" treatment shown:",
    caption = "Source: Kenya Voter Registration Experiment")


```
